version: "3.9"

services:
  frontend:
    container_name: teebay-client
    image: teebay-client
    build:
      context: ./teebay-client
      dockerfile: client.dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    container_name: teebay-server
    image: teebay-server
    build:
      context: ./teebay-server
      dockerfile: server.dockerfile
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://teebay:teebay@teebay-db:5432/teebay?schema=public
      - PORT=4000
      - JWT_SECRET=b94255334c1430f2a4fe85d1f31a18575ec2ee058835867e721d5f0a2a6bfe89eaea18ff6ff72426f7c3b2aecd3034395dea6f64818e288bc869a21b71129bf53c9143e2c13f49f8d3ce4ff6d9dd0b5639f6f81ef2bdf08fa464bdf2ab1aebf62c438c650cebb8ce7ba80f379309abfaa7abccf10653afc5879249454d964aa2d072e1d80fe4742ef038d19efe0b203221f6d028f3b8e32bacc76b33671ecefba16639893571fca968bb50bf4f84ea872209d5fc3c38a3f881330c080b3e2db3f66fb1b07c9e36e4116fdcad2129cf175c8e6fb987988e681d72e7d53bf454a2457755bfb2d08d5b1abd85f406072d83011fefc58edba7f9927e5649bfbdfbcd
    depends_on:
      - db

  db:
    container_name: teebay-db
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: teebay
      POSTGRES_PASSWORD: teebay
      POSTGRES_DB: teebay
    ports:
      - "5432:5432"
    volumes:
      - pd_data:/var/lib/postgresql/data

volumes:
  pd_data: {}
